### ISSUE TITLE
Documentation requirements

### ISSUE THREAD

**Issue by gmrukwa** [maldi-team/msi-divik#5]
The task is to specify documentation comments requirements.

**Comment by gmrukwa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prepare documentation requirements](https://trello.com/c/fMOqxhMS/32-prepare-documentation-requirements)

**Comment by gmrukwa** [comment]
https://github.com/maldi-team/msi-divik/wiki/documentation-general-information

**Comment by Sand3r-** [comment]
I have some doubts if the syntax of ///<summary></summary> works for doxygen at C++
